openarc: Set `BIND_8_COMPAT` CFLAG on Darwin
This is needed to resolve the following errors when compiling on Darwin:

```
libopenarc/arc-dns.c:176:29: error: use of undeclared identifier 'HFIXEDSZ'
  176 |     unsigned char      qbuf[HFIXEDSZ + MAXPACKET];
      |                             ^~~~~~~~
libopenarc/arc-dns.c:183:29: error: use of undeclared identifier 'QUERY'
  183 |     n = res_nmkquery(statp, QUERY, query, C_IN, type, NULL, 0, NULL, qbuf,
      |                             ^~~~~
libopenarc/arc-dns.c:183:43: error: use of undeclared identifier 'C_IN'
  183 |     n = res_nmkquery(statp, QUERY, query, C_IN, type, NULL, 0, NULL, qbuf,
```